### PR TITLE
Feat: application trait status

### PR DESCRIPTION
**Pull request by zhiyuone**
Signed-off-by: Zhiyu Wang <zhiyuwang.newbis@gmail.com>

### Description of your changes
image

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary.
- [x] Run `yarn lint` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by barnettZQG** [comment]
@zhiyuone It's better that shows the trait status in the sub-table of the component row, so there is a clearer hierarchy.

**Comment by zhiyuone** [comment]
> @zhiyuone It's better that shows the trait status in the sub-table of the component row, so there is a clearer hierarchy.

@barnettZQG I tried switching to tree table, but it has a problem with indentation

**Comment by barnettZQG** [comment]
@zhiyuone you could reference the instances page.

**Comment by zhiyuone** [comment]
@barnettZQG  It's a bit ugly for me to use a sub table here, I prefer a compact table

**Comment by zhiyuone** [comment]
Temporarily closed due to inability to resolve indentation issues.

**Comment by barnettZQG** [comment]
@zhiyuone can you create an issue for this.

**Pull request closed without merging**
